// <auto-generated />
using System;
using MegaDesk3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MegaDesk3.Migrations
{
    [DbContext(typeof(MegaDeskContext))]
    [Migration("20190615213911_surface-material-update")]
    partial class surfacematerialupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MegaDesk3.Models.Desk", b =>
                {
                    b.Property<int>("DeskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Depth");

                    b.Property<int>("NumberOfDrawers");

                    b.Property<int?>("SurfaceMaterialId");

                    b.Property<int>("Width");

                    b.HasKey("DeskId");

                    b.HasIndex("SurfaceMaterialId");

                    b.ToTable("Desks");
                });

            modelBuilder.Entity("MegaDesk3.Models.DeskQuote", b =>
                {
                    b.Property<int>("DeskQuoteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("DeskId");

                    b.Property<decimal>("QuotePrice");

                    b.Property<int>("RushOrderType");

                    b.HasKey("DeskQuoteId");

                    b.HasIndex("DeskId");

                    b.ToTable("DeskQuotes");
                });

            modelBuilder.Entity("MegaDesk3.Models.SurfaceMaterial", b =>
                {
                    b.Property<int>("SurfaceMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<decimal>("PriceRate");

                    b.HasKey("SurfaceMaterialId");

                    b.ToTable("SurfaceMaterials");
                });

            modelBuilder.Entity("MegaDesk3.Models.Desk", b =>
                {
                    b.HasOne("MegaDesk3.Models.SurfaceMaterial", "SurfaceMaterial")
                        .WithMany()
                        .HasForeignKey("SurfaceMaterialId");
                });

            modelBuilder.Entity("MegaDesk3.Models.DeskQuote", b =>
                {
                    b.HasOne("MegaDesk3.Models.Desk", "Desk")
                        .WithMany()
                        .HasForeignKey("DeskId");
                });
#pragma warning restore 612, 618
        }
    }
}
